n1 = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n1))
print(n1, 'É composto por espaços? ', n1.isspace())
print(n1, 'É alfabético? ', n1.isalpha())
print(n1, 'É numérico? ', n1.isalnum())
print(n1, 'É numéro decimal? ', n1.isdecimal())
print(n1, 'Está em caixa alta? ', n1.isupper())
print(n1, 'Está em caixa baixa? ', n1.islower())
print(n1, 'É alfanumérico? ', n1.isalnum())